### ISSUE TITLE
CGPS digital epidemiology workshop

### ISSUE THREAD

**Issue by flashton2003** [lskatz/awesome-bioinformatics-education#5]
Name - Centre for Genomic Pathogen Surveillance digital epidemiology workshop
URL - https://cgps-group.github.io/digitalepiworkshop/
Why its good - Really nice integrated exercises, using EpiCollect, DataFlo, PathogenWatch, Microreact.
File under -  genomic epidemiology.

**Comment by lskatz** [comment]
Thank you! Done!
